# Generated by Django 4.0.4 on 2022-07-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='idx',
            field=models.IntegerField(default=0),
        ),
    ]
